### ISSUE TITLE
Remove the doc feature for all crates

### ISSUE THREAD

**Issue by pksunkara** [pksunkara/reign#36]
Blocked by https://github.com/rust-lang/rust/issues/78835

**Comment by pksunkara** [comment]
Fixed by https://github.com/rust-lang/rust/pull/83366

**Comment by jyn514** [comment]
> Fixed by [rust-lang/rust#83366](https://github.com/rust-lang/rust/pull/83366) for 1.53.0

That PR hasn't been merged yet, and may not land in 1.53.

**Comment by pksunkara** [comment]
Yeah, I am subscribed to the PR and will keep track of it. Thanks for the info.
